### ISSUE TITLE
Link to Mermaid & TiddlyWiki Demo

### ISSUE THREAD

**Issue by tobibeer** [gt6796c/mermaid-tw5#1]
Hi @gt6796c, could you please fix the link in the readme to:

https://knsv.github.io/mermaid/

Also, it would be nice to see a demo of this somewhere, e.g. here on GH.

**Comment by gt6796c** [comment]
Updated URL and added demo syntax to README.md. The example.tid already has usage for the TW environment.

**Comment by tobibeer** [comment]
@gt6796c, thx
